---
- hosts: node-1
  user: ansible
  become: yes
  tasks:
    #Installing required Packages
  - name: "Installing Docker Prerequisite packages"
    yum:
    name: "{{ item }}"
    state: latest
    with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    #configure YUM for downloading Docker
  - name: "Configuring docker-ce repo"
    get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
    #Installing Docker
  - name: " Installing Docker latest version"
    yum:
    name: docker-ce
    state: present
    #Starting Docker
  - name: " Starting and Enabling Docker service"
    service:
    name: docker
    state: started
    enabled: yes
